runtime: python
env: flex
entrypoint: gunicorn -b :$PORT covid_help.wsgi --worker-class gevent --timeout 20

beta_settings:
  cloud_sql_instances: lifenest-315103:asia-south1:lifenest-instance

runtime_config:
  python_version: 3