# Generated by Django 3.0.2 on 2021-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('verifiedPhone', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('verifiedEmail', models.BooleanField(default=False)),
                ('instagramHandle', models.CharField(blank=True, max_length=20)),
                ('facebookHandle', models.CharField(blank=True, max_length=20)),
                ('needOxygen', models.BooleanField(default=False)),
                ('needMedications', models.BooleanField(default=False)),
                ('needRemdevsir', models.BooleanField(default=False)),
                ('needHospitalBeds', models.BooleanField(default=False)),
                ('needVentilatorBeds', models.BooleanField(default=False)),
                ('needFoodOrdering', models.BooleanField(default=False)),
                ('needFoodDelivery', models.BooleanField(default=False)),
                ('needTransportation', models.BooleanField(default=False)),
                ('needAmbulance', models.BooleanField(default=False)),
                ('needDonations', models.BooleanField(default=False)),
                ('needPlasma', models.BooleanField(default=False)),
                ('needLabTests', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('verifiedPhone', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('verifiedEmail', models.BooleanField(default=False)),
                ('instagramHandle', models.CharField(blank=True, max_length=20)),
                ('facebookHandle', models.CharField(blank=True, max_length=20)),
                ('isFree', models.BooleanField(default=False)),
                ('isOxygen', models.BooleanField(default=False)),
                ('isMedications', models.BooleanField(default=False)),
                ('isRemdevsir', models.BooleanField(default=False)),
                ('isHospitalBeds', models.BooleanField(default=False)),
                ('isVentilatorBeds', models.BooleanField(default=False)),
                ('isFoodOrdering', models.BooleanField(default=False)),
                ('isFoodDelivery', models.BooleanField(default=False)),
                ('isTransportation', models.BooleanField(default=False)),
                ('isAmbulance', models.BooleanField(default=False)),
                ('isDonations', models.BooleanField(default=False)),
                ('isPlasma', models.BooleanField(default=False)),
                ('isLabTests', models.BooleanField(default=False)),
            ],
        ),
    ]
