# Generated by Django 3.2.3 on 2021-05-22 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Delhi', max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='OTP verification will be required as next step. Format: +919999999999', max_length=20, region=None, unique=True)),
                ('instagramHandle', models.URLField(blank=True)),
                ('facebookHandle', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('verifiedPhone', models.BooleanField(default=False)),
                ('humanVerified', models.BooleanField(default=False)),
                ('verifiedEmail', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False, help_text='I agree to provide the following data to the potential people who might be in need of the services.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='OTP verification will be required as next step. Format: +919999999999', max_length=20, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now=True)),
                ('name', models.CharField(choices=[('Oxygen', 'Oxygen'), ('Medications (no Remdesivir)', 'Medications (no Remdesivir)'), ('Remdesivir', 'Remdesivir'), ('Hospital Beds', 'Hospital Beds'), ('Ventilator Beds', 'Ventilator Beds'), ('Home-made Food', 'Home-made Food'), ('Ambulance', 'Ambulance'), ('Monetary Donations', 'Monetary Donations'), ('Plasma Donations', 'Plasma Donations'), ('Laboratory Testing', 'Laboratory Testing')], default='Oxygen', max_length=70)),
                ('additional_details', models.CharField(blank=True, max_length=5000)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.participant')),
            ],
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['state'], name='state_supplier'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone'], name='phone_supplier'),
        ),
    ]
