# Generated by Django 3.2.3 on 2021-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
        migrations.AddField(
            model_name='participant',
            name='supplier_services',
            field=models.ManyToManyField(to='covid.Service'),
        ),
    ]
