# Generated by Django 3.0.2 on 2021-04-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210426_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
