# Generated by Django 3.2.3 on 2021-05-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210522_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='supplier_services',
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.participant'),
        ),
    ]
