# Generated by Django 3.0.2 on 2021-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210513_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='humanVerified',
            field=models.BooleanField(default=False),
        ),
    ]
