# Generated by Django 3.0.2 on 2021-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210426_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requester',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='requester',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='requester',
            index_together={('firstName', 'lastName')},
        ),
        migrations.AlterIndexTogether(
            name='supplier',
            index_together={('firstName', 'lastName')},
        ),
        migrations.AddIndex(
            model_name='requester',
            index=models.Index(fields=['state'], name='state_requester'),
        ),
        migrations.AddIndex(
            model_name='requester',
            index=models.Index(fields=['firstName'], name='first_name_requester'),
        ),
        migrations.AddIndex(
            model_name='requester',
            index=models.Index(fields=['lastName'], name='last_name_requester'),
        ),
        migrations.AddIndex(
            model_name='requester',
            index=models.Index(fields=['phone'], name='phone_requester'),
        ),
        migrations.AddIndex(
            model_name='requester',
            index=models.Index(fields=['email'], name='email_requester'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['state'], name='state_supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['firstName'], name='first_name_supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['lastName'], name='last_name_supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['phone'], name='phone_supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='email_supplier'),
        ),
        migrations.RemoveField(
            model_name='requester',
            name='services',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='services',
        ),
    ]
