# Generated by Django 3.0.2 on 2021-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_requester_humanverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
