# Generated by Django 3.0.2 on 2021-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210426_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requesters',
            field=models.ManyToManyField(to='covid.Requester'),
        ),
        migrations.AddField(
            model_name='service',
            name='suppliers',
            field=models.ManyToManyField(to='covid.Supplier'),
        ),
    ]
