# Generated by Django 3.0.2 on 2021-04-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20210426_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='service',
            name='isDelivery',
        ),
        migrations.RemoveField(
            model_name='service',
            name='isFree',
        ),
    ]
