# Generated by Django 3.0.2 on 2021-05-14 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0005_requester_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Delhi', max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('instagramHandle', models.URLField(blank=True)),
                ('facebookHandle', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('verifiedPhone', models.BooleanField(default=False)),
                ('humanVerified', models.BooleanField(default=False)),
                ('verifiedEmail', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False, help_text='I agree to provide the following data to the potential suppliers.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['state'], name='state_volunteer'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['phone'], name='phone_volunteer'),
        ),
    ]
