# Generated by Django 3.2.3 on 2021-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_alter_service_pricing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_type',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery',
            field=models.BooleanField(default=False, help_text='Do you deliver?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', max_length=10),
        ),
    ]
