# Generated by Django 3.0.2 on 2021-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210426_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='requesters',
        ),
        migrations.RemoveField(
            model_name='service',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='requester',
            name='consent',
            field=models.BooleanField(default=False, help_text='I agree to provide the following data to the potential suppliers.'),
        ),
        migrations.AddField(
            model_name='requester',
            name='services',
            field=models.ManyToManyField(to='covid.Service'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='consent',
            field=models.BooleanField(default=False, help_text='I agree to provide the following data to the potential people who might be in need of the services.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='services',
            field=models.ManyToManyField(to='covid.Service'),
        ),
    ]
