# Generated by Django 3.0.2 on 2021-05-14 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210514_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in format +91-9999999999.', regex='^(\\+\\d{1,3})?-?\\s?\\d{8,13}')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in format +919999999999.', regex='^(\\+\\d{1,3})?-?\\s?\\d{8,13}')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in format +919999999999.', regex='^(\\+\\d{1,3})?-?\\s?\\d{8,13}')]),
        ),
    ]
