# Generated by Django 3.2.3 on 2021-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210522_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', max_length=10),
        ),
    ]
