# Generated by Django 3.0.2 on 2021-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210426_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='facebookHandle',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='instagramHandle',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='facebookHandle',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='instagramHandle',
            field=models.URLField(blank=True),
        ),
    ]
