# Generated by Django 3.2.3 on 2021-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_alter_service_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
