# Generated by Django 3.0.2 on 2021-05-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_supplier_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='services',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='requester',
            field=models.ManyToManyField(to='covid.Requester'),
        ),
        migrations.AddField(
            model_name='service',
            name='supplier',
            field=models.ManyToManyField(to='covid.Supplier'),
        ),
    ]
