# Generated by Django 3.0.2 on 2021-05-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_auto_20210509_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='humanVerified',
            field=models.BooleanField(default=False),
        ),
    ]
