# Generated by Django 3.2.3 on 2021-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0010_service_humanverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='payment',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Andhra Pradesh', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_details',
            field=models.CharField(blank=True, help_text='Any additional details or restrictions about the availability of your service.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', help_text='Is your delivery paid or free?', max_length=10),
        ),
    ]
