# Generated by Django 3.2.3 on 2021-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_auto_20210522_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='consent',
            field=models.BooleanField(default=False, help_text='I acknowledge that the details entered by me are correct. In case of spam reports against this posting, I am bound to being banned from this platform.'),
        ),
    ]
