# Generated by Django 3.0.2 on 2021-05-09 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_supplier_humanverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in format +919999999999.', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
