# Generated by Django 3.2.3 on 2021-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_service_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='twitterHandle',
            field=models.URLField(blank=True),
        ),
    ]
