# Generated by Django 3.0.2 on 2021-05-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_auto_20210509_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='city',
            field=models.CharField(default='Rajkot', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='Rajkot', max_length=20),
            preserve_default=False,
        ),
    ]
