# Generated by Django 3.2.3 on 2021-05-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_participant_twitterhandle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='facebookHandle',
            field=models.URLField(blank=True, help_text='Valid URL expected.'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='instagramHandle',
            field=models.URLField(blank=True, help_text='Valid URL expected.'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='twitterHandle',
            field=models.URLField(blank=True, help_text='Valid URL expected.'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='website',
            field=models.URLField(blank=True, help_text='Valid URL expected.'),
        ),
    ]
