# Generated by Django 3.2.3 on 2021-05-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0014_auto_20210523_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='humanVerified',
        ),
        migrations.RemoveField(
            model_name='service',
            name='humanVerified',
        ),
    ]
