# Generated by Django 3.2 on 2021-05-21 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0014_auto_20210520_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Delhi', max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='OTP verification will be required as next step. Format: +919999999999', max_length=20, region=None, unique=True)),
                ('instagramHandle', models.URLField(blank=True)),
                ('facebookHandle', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('verifiedPhone', models.BooleanField(default=False)),
                ('humanVerified', models.BooleanField(default=False)),
                ('verifiedEmail', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False, help_text='I agree to provide the following data to the potential people who might be in need of the services.')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='service',
            name='supplier',
        ),
        migrations.AddField(
            model_name='service',
            name='additional_details',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.DeleteModel(
            name='Requester',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.AddField(
            model_name='participant',
            name='requester_services',
            field=models.ManyToManyField(related_name='requester_services', to='covid.Service'),
        ),
        migrations.AddField(
            model_name='participant',
            name='supplier_services',
            field=models.ManyToManyField(related_name='supplier_services', to='covid.Service'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['state'], name='state_supplier'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone'], name='phone_supplier'),
        ),
    ]
