# Generated by Django 3.2.3 on 2021-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0016_participant_num_scams'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='num_helps',
            field=models.IntegerField(default=0),
        ),
    ]
