# Generated by Django 3.2.3 on 2021-05-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0017_participant_num_helps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', help_text='Is the resource paid or available for free?', max_length=10),
        ),
    ]
