# Generated by Django 3.2.3 on 2021-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0018_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='scam_votes',
            field=models.ManyToManyField(related_name='scam_votes_participants', to='covid.Participant'),
        ),
    ]
