# Generated by Django 3.2.3 on 2021-05-26 05:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0020_service_help_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, unique=True)),
                ('reason', models.CharField(help_text='Please explain the reason for marking this number as spam.', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='spam_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='You cannot change this later. OTP verification will be required as next step. Format: +919999999999', max_length=20, region=None, unique=True),
        ),
    ]
