# Generated by Django 3.2.3 on 2021-05-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0021_auto_20210526_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spammer',
        ),
    ]
