# Generated by Django 3.2.3 on 2021-05-26 05:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0022_delete_spammer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
                ('reason', models.CharField(help_text='Please explain the reason for marking this number as spam.', max_length=500)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.participant')),
            ],
        ),
    ]
