# Generated by Django 3.2.3 on 2021-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0023_spammer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='spam_reports',
            new_name='spam_reports_given',
        ),
        migrations.AddField(
            model_name='participant',
            name='spam_reports_received',
            field=models.IntegerField(default=0),
        ),
    ]
