# Generated by Django 3.2.3 on 2021-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0024_auto_20210526_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='spammer',
            name='consent',
            field=models.BooleanField(default=False, help_text='I confirm that the information entered by me is correct and not trying to mislead other members on this platform in any manner.'),
        ),
    ]
