# Generated by Django 3.2.3 on 2021-05-26 17:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0025_spammer_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='spammer',
            name='date_reported',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spammer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='The spam report will not be registered if you have already filed a report for the same contact before.', max_length=20, region=None),
        ),
    ]
