# Generated by Django 3.2.3 on 2021-05-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0027_alter_spammer_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spammer',
            options={'ordering': ('date_reported',)},
        ),
    ]
