# Generated by Django 3.2.3 on 2021-05-29 15:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0029_alter_spammer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='OTP verification will be required to create postings. Format: +919999999999', max_length=20, region=None, unique=True),
        ),
    ]
