# Generated by Django 3.2.3 on 2021-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0031_participant_lastphoneupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='lastPhoneUpdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
