# Generated by Django 3.2.3 on 2021-05-29 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0032_alter_participant_lastphoneupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='lastPhoneUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
