# Generated by Django 3.2.3 on 2021-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0034_auto_20210530_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='help_votes',
            field=models.ManyToManyField(blank=True, related_name='help_votes_participants', to='covid.Participant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Oxygen', 'Oxygen'), ('Medications (no Remdesivir)', 'Medications (no Remdesivir)'), ('Mucomycosis Drugs', 'Mucomycosis Drugs'), ('Hospital Beds', 'Hospital Beds'), ('Ventilator Beds', 'Ventilator Beds'), ('Home-made Food', 'Home-made Food'), ('Ambulance', 'Ambulance'), ('Monetary Donations', 'Monetary Donations'), ('Laboratory Testing', 'Laboratory Testing'), ('Vaccine Clinics', 'Vaccine Clinics'), ('Tiffin Services', 'Tiffin Services'), ('Restaurants', 'Restaurants'), ('Counselling Services', 'Counselling Services')], default='Oxygen', max_length=70),
        ),
        migrations.AlterField(
            model_name='service',
            name='scam_votes',
            field=models.ManyToManyField(blank=True, related_name='scam_votes_participants', to='covid.Participant'),
        ),
    ]
